# Generated by Django 5.2 on 2025-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated_article', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
